name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MINEIROS_TESTING_AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.MINEIROS_TESTING_AWS_ACCESS_KEY_ID }}

concurrency:
  group: terraform-module-template
  cancel-in-progress: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pre-commit
        run: make test/pre-commit

  unit-tests:
    needs: pre-commit
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  #     - name: Check for Terraform file changes
  #       uses: getsentry/paths-filter@v2
  #       id: changes
  #       with:
  #         token: ${{ github.token }}
  #         filters: |
  #           terraform:
  #             - '**/*.tf'
  #             - '**/*.go'
  #             - 'go.mod'
  #             - 'go.sum'

  #     - name: Run Unit Tests
  #       if: steps.changes.outputs.terraform == 'true'
  #       run: make test/unit-tests
